### ISSUE TITLE
ImportError: DLL load failed while importing quant_cuda

### ISSUE THREAD

**Issue by ghost** [jllllll/GPTQ-for-LLaMa-Wheels#2]
hi buddy.
After install this whl, i tried to import it in python but got this:

(py310) E:\Code\BELLE\gptq>python
Python 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>import torch
>import quant_cuda

Traceback (most recent call last):
  File stdin, line 1, in <module>
ImportError: DLL load failed while importing quant_cuda

anyone has some ideas how to config it？thank you!

**Comment by jllllll** [comment]
Best I can do is point you to projects that utilize it.
https://github.com/YellowRoseCx/KoboldAI/blob/yr4bit/aiserver.py#L91
https://github.com/oobabooga/text-generation-webui/blob/main/modules/GPTQ_loader.py#L12

I've had issues in the past with getting the wheel to work when it was installed outside of the GPTQ-for-LLaMa repo folder.
Clone this fork: https://github.com/oobabooga/GPTQ-for-LLaMa.git and place the wheel in it's folder before installing it.

**Comment by ghost** [comment]
thx! found its something wrong with the windows support of [bitsandbytes](https://github.com/TimDettmers/bitsandbytes)
after installed whl from https://github.com/acpopescu/bitsandbytes/releases/tag/v0.37.2-win.1, everything is ok！

**Comment by jllllll** [comment]
> thx! found its something wrong with the windows support of [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) after installed whl from https://github.com/acpopescu/bitsandbytes/releases/tag/v0.37.2-win.1, everything is ok！

I also have a wheel built from that source. I fixed an issue with CUDA detection in conda environments in my version.
https://github.com/jllllll/bitsandbytes-windows-webui
